# Generated by Django 3.2.9 on 2021-12-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211204_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='nomer',
            field=models.CharField(default='', max_length=17),
        ),
    ]
