# Generated by Django 3.2.9 on 2021-12-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_books_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='file',
        ),
        migrations.AddField(
            model_name='books',
            name='book',
            field=models.TextField(default='', max_length=120000),
        ),
    ]
