# Generated by Django 3.2.9 on 2021-12-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_book_disciplines_bookis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplines',
            name='bookis',
        ),
    ]
