# Generated by Django 3.2.9 on 2021-12-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_disciplines_bookis'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
